### solve the longest common subsequence problem

In [30]:
import numpy as np

In [33]:
def createScoreMatrix(list1, list2, debug=False):
    lenList1, lenList2 = len(list1), len(list2)
    #initialize matrix
    scoreMatrix = np.zeros((len(list1)+1, len(list2)+1), dtype=int)
    #populate the matrix
    for i, x in enumerate(list1):
        for j, y in enumerate(list2):
            if x == y:
                scoreMatrix[i+1][j+1] = scoreMatrix[i][j]+1
            else:
                scoreMatrix[i+1][j+1] = max(scoreMatrix[i][j+1], scoreMatrix[i+1][j])
    if debug:
        print(scoreMatrix)
    return scoreMatrix

list1=[1, 2, 4, 6,7,8,0]
list2=[4,5,7,1,2,0]
print(createScoreMatrix(list1, list2))

[[0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1]
 [0 0 0 0 1 2 2]
 [0 1 1 1 1 2 2]
 [0 1 1 1 1 2 2]
 [0 1 1 2 2 2 2]
 [0 1 1 2 2 2 2]
 [0 1 1 2 2 2 3]]


In [34]:
def traceBack(list1, list2, scoreMatrix):
    '''
    Return:
         alignedList1, alignedList2, commonSub
    '''
    commonSub=[]
    alignedList1 = []
    alignedList2 = []
    i, j = len(list1), len(list2)
    if i == 0 or j == 0:
        return list1, list2, commonSub
    else:
        while i != 0 and j != 0:
            if list1[i-1] == list2[j-1]:
                commonSub.append(list1[i-1])
                alignedList1.append(list1[i-1])
                alignedList2.append(list2[j-1])
                i -= 1
                j -= 1
            elif scoreMatrix[i][j] == scoreMatrix[i-1][j-1]:
                alignedList1.append(list1[i-1])
                alignedList2.append(list2[j-1])
                i -= 1
                j -= 1
            elif scoreMatrix[i][j] == scoreMatrix[i-1][j]:
                alignedList1.append(list1[i-1])
                alignedList2.append('_')
                i -= 1
            else: #scoreMatrix[i][j] == scoreMatrix[i][j-1]:
                alignedList1.append('_')
                alignedList2.append(list2[j-1])
                j -= 1
                
        #己回滋到最左一行，或最上一列，但未到达0, 0 位置
        while i > 0:
            alignedList1.append(list1[i-1])
            i -= 1
        while j > 0:
            alignedList2.append(list2[j-1])
            j -= 1
    alignedList1.reverse()
    alignedList2.reverse()
    commonSub.reverse()
    return alignedList1, alignedList2, commonSub
    
    
list1=[3, 1, 2, 4, 6,7,8,0]
list2=[3, 4,5,7,1,2,0]
alignedList1, alignedList2, commonSub = traceBack(list1, list2, createScoreMatrix(list1, list2))
print(alignedList1)
print(alignedList2)
print(commonSub)

[3, 1, 2, 4, 6, 7, '_', 8, 0]
[3, '_', '_', 4, 5, 7, 1, 2, 0]
[3, 4, 7, 0]


In [35]:
#这里我们只打印一个结果，实际上可能出现多个结果
#要打印多个结果时，就要像smith-waterman算法一样，从scoreMatrix中找到分值最大的单元格，然后再分别进行回溯求能匹配上的子序列。
#当有多个结果时，在scoreMatrix矩阵中的分值最大的有多个单元格
def lcs_one(list1, list2, debug=False):
    return traceBack(list1, list2, createScoreMatrix(list1, list2, debug))

In [36]:
text1 = "this is a test for text alignment from xxxx"
text2 = "Hi, try A test for alignment , Heirish"
list1 = text1.lower().split(" ")
list2 = text2.lower().split(" ")
alignedList1, alignedList2, commonSub = lcs_one(list1, list2)
print(alignedList1)
print(alignedList2)
print(commonSub)

['this', 'is', 'a', 'test', 'for', 'text', 'alignment', 'from', 'xxxx']
['hi,', 'try', 'a', 'test', 'for', '_', 'alignment', ',', 'heirish']
['a', 'test', 'for', 'alignment']


In [37]:
list1=list("GGATCGA")
list2=list("GAATTCAGTTA")
alignedList1, alignedList2, commonSub = lcs_one(list1, list2)
print(alignedList1)
print(alignedList2)
print(commonSub)

['G', 'G', 'A', '_', 'T', 'C', '_', 'G', '_', '_', 'A']
['G', 'A', 'A', 'T', 'T', 'C', 'A', 'G', 'T', 'T', 'A']
['G', 'A', 'T', 'C', 'G', 'A']


In [38]:
list1 = list("GCCCTAGCG")
list2 = list("GCGCAATG")
alignedList1, alignedList2, commonSub = lcs_one(list1, list2)
print(alignedList1)
print(alignedList2)
print(commonSub)

['G', 'C', 'C', 'C', 'T', 'A', 'G', 'C', 'G']
['G', 'C', 'G', 'C', '_', 'A', 'A', 'T', 'G']
['G', 'C', 'C', 'A', 'G']


In [39]:
list1 = list("algorithm")
list2 = list("alignment")
alignedList1, alignedList2, commonSub = lcs_one(list1, list2)
print(alignedList1)
print(alignedList2)
print(commonSub)

['a', 'l', '_', 'g', '_', 'o', 'r', 'i', 't', 'h', 'm']
['a', 'l', 'i', 'g', 'n', 'm', 'e', 'n', 't', '_', '_']
['a', 'l', 'g', 't']


In [40]:
list1 = list("ABCBDAB")
list2 = list("BDCABA")
alignedList1, alignedList2, commonSub = lcs_one(list1, list2, True)
print(alignedList1)
print(alignedList2)
print(commonSub)

[[0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1]
 [0 1 1 1 1 2 2]
 [0 1 1 2 2 2 2]
 [0 1 1 2 2 3 3]
 [0 1 2 2 2 3 3]
 [0 1 2 2 3 3 4]
 [0 1 2 2 3 4 4]]
['A', 'B', '_', 'C', '_', 'B', 'D', 'A', 'B']
['B', 'D', 'C', 'A', 'B', '_', 'A', '_']
['B', 'C', 'B', 'A']
